### ISSUE TITLE
smtp errro 554

### ISSUE THREAD

**Issue by aminaqi** [3s3s/opentrade#113] opened 2018-09-04 13:48 UTC
![image](https://user-images.githubusercontent.com/42599315/45035268-d6b6de80-b06e-11e8-813e-db778871bf4b.png)
please help me fix it

**Comment by jonn4y** [comment] 2018-09-04 14:54
duplicate of 
https://github.com/3s3s/opentrade/issues/112

**Comment by parwezmansuri** [comment] 2018-09-04 16:53
Set true and try

https://github.com/3s3s/opentrade/blob/master/server/constants.js#L11

**Comment by aminaqi** [comment] 2018-09-04 18:12
Thanks i think it worked fine, now do what? i'm using digitalocean ubuntu so open in which browser localhost:40403?
![image](https://user-images.githubusercontent.com/42599315/45049420-cbc27500-b093-11e8-82a0-d8d65580d5df.png)

**Comment by parwezmansuri** [comment] 2018-09-04 18:18
Your vpsip:40443

**Comment by aminaqi** [comment] 2018-09-05 08:11
![image](https://user-images.githubusercontent.com/42599315/45079971-087c8380-b109-11e8-8208-561a80059224.png)
???

**Comment by aminaqi** [comment] 2018-09-05 08:16
show the above error while using VPN and without VPN i can't get connected
![image](https://user-images.githubusercontent.com/42599315/45080224-aa03d500-b109-11e8-880e-0349fa66196d.png)

**Comment by parwezmansuri** [comment] 2018-09-05 08:47
You set first email id
Example : support email yourname@gmail.com
No reply email  yourname2@gmail.com

Then run node main.js it's work with or without vpn

**Comment by aminaqi** [comment] 2018-09-05 10:17
it works fine but i meant when i want to open it in browser get that error
![image](https://user-images.githubusercontent.com/42599315/45087216-64033d00-b11a-11e8-92bb-3282142dda82.png)
i'm using putty to connect to digitalocean droplet, but i really don't how access opentrade in my browser, 
i also receive email notifications too

**Comment by CryptorClub** [comment] 2018-09-05 10:27
Be sure, that this port is opened and you configure your nginx server.
https://medium.com/@abhaytalreja/configure-digital-ocean-for-ssl-https-meteor-app-as-a-bonus-part-4-6b5a00b581ef

**Comment by parwezmansuri** [comment] 2018-09-05 10:59
How to setup SSL for opentrade domain

**Comment by CryptorClub** [comment] 2018-09-05 11:33
I've setup it using this tutorial, you need to paste External IP instead of domain, if you haven't
https://medium.com/@abhaytalreja/configure-digital-ocean-for-ssl-https-meteor-app-as-a-bonus-part-4-6b5a00b581ef

**Comment by aminaqi** [comment] 2018-09-05 11:38
@CryptorClub  can you give me your email?
i can't fix the problem because of lack of knowledge, i give you my ubunta ip address and login details please fix my problem i really appreciate that
Thanks

**Comment by aminaqi** [comment] 2018-09-05 11:38
aminmr1375@gmail.com

**Comment by CryptorClub** [comment] 2018-09-05 11:54
@aminaqi just run this command
`curl ipinfo.io/ip`
You will get your servers IP address
Then type in browser this ip with port, like you do before. You need, to understand wow to setup it, if you want to manage it

**Comment by coinnetworkpw** [comment] 2018-09-05 12:53
@aminaqi 
I sent you email, I fixed it

Guys for SSL you just install nginx and install letsencrypt for nginx, you will have certificates and everything.there are many tutorials on digitalocean for ubuntu

**Comment by jonn4y** [comment] 2018-09-05 14:00
@coinnetworkpw dont forget to set a cron job to automatically redo the certificate every 90 days ;)

**Comment by parwezmansuri** [comment] 2018-09-05 14:03
I get error after setup unexpected json

**Closed** 2018-09-05 15:56 UTC

**Comment by coinnetworkpw** [comment] 2018-09-06 09:42
@jonn4y I know :)
This is not our first time doing it.
We are setting up exchanges for our clients from peatio and this script since last year and always using nginx.

@parwezmansuri do you have your coin deamons running ?

**Comment by parwezmansuri** [comment] 2018-09-06 09:47
Last time I check exchange it's work other coin deamons but at this time my vps stuck so still I am waiting for resolve my vps issue. Then after I setup exchange.
